---
#########################################
# options for knitting a single chapter #
#########################################
output:
  bookdown::html_document2: default
  bookdown::word_document2: default
  bookdown::pdf_document2:
    template: templates/brief_template.tex
documentclass: book
bibliography: references.bib
---

``` {r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(readr)
ikea <- read_delim("ikea.csv", ";", 
                   escape_double = FALSE, 
                   trim_ws = TRUE,
                   col_types = cols(
                     name = col_factor(),
                     category = col_factor(),
                     designer = col_factor()
                   )
                  )

# tidy data

## tidy designer
tidy_ikea <- ikea

tidy_ikea$designer[grepl("\\d",tidy_ikea$designer)]<- NA


tidy_ikea <- tidy_ikea %>%
  separate(designer, c("d1", "d2", "d3", "d4", "d5", "d6", "d7"), sep = "/")

tidy_ikea[ , 11:17][tidy_ikea[ , 11:17] == "IKEA of Sweden" ] <- NA
tidy_ikea[ , 11:17] <- t(apply(tidy_ikea[ , 11:17], 1, function(x) c(sort(x[x!='']), x[x==''])))

tidy_ikea <- tidy_ikea %>%
  unite(col = "designer", d1, d2, d3, d4, d5, d6, d7, sep = ", ", na.rm = TRUE)

tidy_ikea$designer[tidy_ikea$designer == ""] <- NA

## convert other colors to boolean
tidy_ikea <- tidy_ikea %>%
  mutate(other_colors = other_colors == "Yes")

## convert old price to integer and times 10
tidy_ikea <- tidy_ikea %>%
  mutate(old_price = str_replace(old_price, "SR ", "")) %>%
  mutate(old_price = str_replace_all(old_price, ",", "")) %>%
  mutate(old_price = strtoi(old_price)) %>%
  mutate(old_price = old_price * 10)
  
# transform data columns

# add size in m^3
tidy_ikea <- tidy_ikea %>%
  mutate(size_m3 = round(depth/100 * width/100 * height/100, 2))

# transform price and old price in eur
tidy_ikea <- tidy_ikea %>%
  mutate(price_eur = round(price * 0.23 / 10, 2), old_price_eur = round(old_price * 0.23 / 10, 2))

## select relevant data
tidy_ikea <- tidy_ikea %>%
  select(name, category, price_eur, old_price_eur, sellable_online, other_colors, designer, size_m3)

```

``` {r echo=FALSE, message=FALSE}
# setup color theme
library('RColorBrewer')
num_cols <- 17
mycolors <- colorRampPalette(brewer.pal(12, "Set3"))(num_cols) # add a custom color palette
```


# Introduction {#intro}
``` {r echo=FALSE, fig.cap="Sample plot", out.width="100%", message=FALSE}
ggplot(data = tidy_ikea) +
  geom_bar(mapping = aes(x = other_colors, fill = other_colors), show.legend = FALSE) +
  scale_fill_manual(values = mycolors) +
  theme_minimal() +
  labs(x = "other colors", y = "# of items", title = "Number of Items with Other Colors") 
```