---
output:
  bookdown::html_document2: default
  bookdown::word_document2: default
  bookdown::pdf_document2: 
    template: templates/brief_template.tex
documentclass: book
bibliography: references.bib
---
  
# Discussion {#discussion}
\hfill\textcolor{gray}{by J. Pein}

In this chapter, the results are discussed in connection with the research question. The question that the results were supposed to answer is the following:

*How important are the different features of Ikea products in regard to their price?*

## Feature Importance

The `size_m3` variable is the most important feature. Probably the main reason for this is the size of a product being closely linked to its material cost. Big items are generally more costly to produce, thus leading to a higher selling price and vice versa. Due to the high correlation to the price variable described in section \@ref(collinearity) and section \@ref(relationship), it is worth discussing whether or not to include this variable in a possible predictive analysis model in future research. 

The `designer` variable is the second most important feature. It might seem, that this is due to *overfitting*, since the random forest regression model takes into account around 50 different combinations of designers, partly with a low number of occurences. But according to @Breiman2001 and @Liaw2002 random forest models are robust against overfitting. Further research should be conducted to analyze whether overfitting is present or not.
When looking at the price distribution per designer, in can be clearly seen that the interquartile range (IQR) of price varies for each designer. In addition, the IQR often is smaller than 300€, thus showing a tendency towards a certain price range, which might be the reason for the relatively high feature importance of the designer variable. For the plot, see figure \@ref(fig:price-dist-per-designer).

The data set, which the random forest was trained on, includes around 50 different product names with partly small numbers of occurences. Thus, the relatively high feature importance of the `name` variable might also be caused by overfitting. As discussed above, further research should be conducted to analyze whether this is the case.

`Category` is another feature with a relatively high importance. This is because the different category's price distributions show a clear tendency towards certain price segments (see figure \@ref(fig:price-dist-per-category)), i.e. Wardrobes and beds are generally more expensive than chairs.
To the authors it seems counterintuitive that `designer` and `name` have higher feature importances than the `category` feature, because the IQR in the price distribution per category is often a lot smaller than the IQR of the designer and name price distributions. This also hints towards overfitting of the name and designer variables. However, in the categories with the most occurrences, namely `Wardrobes`, `Sofas & armchairs` and `Beds`, the IQR is relatively large and there are many overlapping prices ranges for different categories, which explains a lower feature importance.

The feature importance of `other_colors` is the second lowest, but still considerable. This still relatively high feature importance might be due to the difference of the mean price and the relatively small IQR (see: figure \@ref(fig:price-dist-other-colors)). On the other hand, there is a large overlapping area within the IQR in the two expressions of `other_colors` possibly reducing the feature importance.

The very low feature importance of the `sellable_online` variable is probably because the low number of occurences of a product being sellable online. Only around 0.6% of the products are sellable online.

## Conclusion

The authors were surprised of the high feature importances of the variables `designer` and `name` computed by the random forest model. The thesis of this being due to overfitting is objected by scientific research [@Breiman2001][@Liaw2002]. If the high feature importance of the variables truly is not due to overfitting, this example backs up @Groemping2009 thesis that random forests are able to discover deeper patterns in the data. These patterns are beyond the boxplot discussion applied here, showing the power of random forests models.

Also, the data was scraped from the arabian Ikea website online, thus this analysis mainly focusses on Ikea products in the Saudi Arabian market. To analyze the geographically independent feature importances, more data should be scraped from other international Ikea websites. The research question of this paper, *How important are the different features of Ikea products in regard to their price?*, could thus not be answered for the global Ikea product market, but for the Saudi Arabian market only. ALso, in further research, the results presented on the feature importance of the predictor variables on the response variable price should be validated by other techniques than the random forest method used in this analysis to get unbiased results. 

Furthermore, based on this analysis a predictive model could be developed which predicts the price of Ikea products in the Saudi Arabian Market based on the features analyzed. This could be used by Ikea internally to analyze if the price of their new product aligns with the prices of the currently available product or by market researchers. 










