---
#####################
## thesis metadata ##
#####################
title: Analyzing the Feature Importance of Different Variables on the Price of Ikea Products
author: Philip Krück, Johannes Pein
degree: B.Sc. Business Informatics (18A-BI)
degreedate: 04.12.2020
lecturer: "Lecturer: Ulf Köther"
groupnumber: "Group Number: 7"
modulename: "Digital Toolbox: Data Business"
matriculationnumbers: "Matriculation Numbers: 3938 (P.Krück), 4001 (J.Pein)"
abbreviations: "front-and-back-matter/abbreviations" # path to .tex file with abbreviations

#######################
## bibliography path ##
#######################
bibliography: references.bib
bibliography-heading-in-pdf: Works Cited

#####################
## PDF formatting  ##
#####################
abstractseparate: false  # include front page w/ abstract for examination schools?
bib-humanities: true   #set to true if you want in-text references formatted as author-year
doi-in-bibliography: true #set to true if you want DOI's to be shown in the bibliography
draft: false # add as DRAFT mark in the footer?
page-layout: nobind #'nobind' for PDF output (equal margins), 'twoside' for two-sided binding (mirror margins and blank pages), leave blank for one-sided binding (left margin > right margin)
hidelinks: true #if false, the PDF output highlights clickable links with a colored border - you will probably want to set this to true for PDF version you wish to physically print
toc-depth: 2 # depth of heading to include in table of contents
lof: true # list of figures in front matter?
lot: true # list of tables in front matter?
mini-toc: fase  # mini-table of contents at start of each chapter? (this just prepares it; you must also add \minitoc after the chapter titles)
mini-lot: false  # mini-list of tables by start of each chapter?
mini-lof: false  # mini-list of figures by start of each chapter?

params:
  corrections: true # set false to stop applying blue background to blocks of corrections

#####################
## output options  ##
#####################
output:
  bookdown::pdf_book:
    template: templates/template.tex
    keep_tex: true
    citation_package: default  
    pandoc_args: ["--lua-filter=scripts_and_filters/correction_filter.lua","--csl", "chicago_footnote.csl"] #remove filter to stop applying blue background to inline corrections
  bookdown::gitbook:
    css: templates/style.css
    config:
      sharing:
        facebook: false
        twitter: yes
        all: false
  bookdown::word_document2:
    toc: true   
link-citations: true
documentclass: book

---


```{r create_chunk_options, include=FALSE, eval=knitr::is_latex_output()}
source('scripts_and_filters/create_chunk_options.R')
source('scripts_and_filters/wrap_lines.R')
```

``` {r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(readr)
ikea <- read_delim("ikea.csv", ";", 
                   escape_double = FALSE, 
                   trim_ws = TRUE,
                   col_types = cols(
                     name = col_factor(),
                     category = col_factor(),
                     designer = col_factor()
                   )
                  )

# tidy data

## tidy designer
tidy_ikea <- ikea

tidy_ikea$designer[grepl("\\d",tidy_ikea$designer)] <- NA


tidy_ikea <- tidy_ikea %>%
  separate(designer, c("d1", "d2", "d3", "d4", "d5", "d6", "d7"), sep = "/")

tidy_ikea[ , 11:17][tidy_ikea[ , 11:17] == "IKEA of Sweden" ] <- NA
tidy_ikea[ , 11:17] <- t(apply(tidy_ikea[ , 11:17], 1, function(x) c(sort(x[x!='']), x[x==''])))

tidy_ikea <- tidy_ikea %>%
  unite(col = "designer", d1, d2, d3, d4, d5, d6, d7, sep = ", ", na.rm = TRUE)

tidy_ikea$designer[tidy_ikea$designer == ""] <- NA

## convert other colors to boolean
tidy_ikea <- tidy_ikea %>%
  mutate(other_colors = other_colors == "Yes")

## convert old price to integer and times 10
tidy_ikea <- tidy_ikea %>%
  mutate(old_price = str_replace(old_price, "SR ", "")) %>%
  mutate(old_price = str_replace_all(old_price, ",", "")) %>%
  mutate(old_price = strtoi(old_price)) %>%
  mutate(old_price = old_price * 10)
  
# transform data columns

# add size in m^3
tidy_ikea <- tidy_ikea %>%
  mutate(size_m3 = round(depth/100 * width/100 * height/100, 2))

# transform price and old price in eur
sr_to_eur_conversion_factor <- 0.24537 # conversion factor from 20.04.2020 (https://www.xe.com/de/currencyconverter/convert/?Amount=1&From=EUR&To=SAR)

tidy_ikea <- tidy_ikea %>%
  mutate(price_eur = round(price * sr_to_eur_conversion_factor / 10, 2), old_price_eur = round(old_price * sr_to_eur_conversion_factor / 10, 2))

## select relevant data
tidy_ikea <- tidy_ikea %>%
  select(name, category, price_eur, old_price_eur, sellable_online, other_colors, designer, size_m3)
```

``` {r echo=FALSE, message=FALSE}
# setup color theme
library('RColorBrewer')
num_cols <- 17
mycolors <- colorRampPalette(brewer.pal(12, "Set3"))(num_cols) # add a custom color palette
```
