`r if(knitr:::is_latex_output()) '\\startappendices'`

`r if(!knitr:::is_latex_output()) '# (APPENDIX) Appendix {-}'` 

<!-- If you feel it necessary to include an appendix, it goes here. The first appendix should include the commands above. -->


# Appendix

```{r price-dist-per-designer, echo = FALSE, warning = FALSE, message = FALSE, results = 'hide', fig.cap="A Plot Showing the Price Distribution per Designer", out.width="100%"}
tidy_ikea %>%
  ggplot(mapping = aes(x = fct_reorder(fct_lump(tidy_ikea$designer, 25), price_eur), y = price_eur, colour = fct_lump(tidy_ikea$designer, 25))) +
    geom_boxplot(width = 0.4, outlier.size = 0.5, outlier.alpha = 0.3,  show.legend = FALSE) +
    theme_minimal() +
    labs(x = "", y = "price in €", fill = "") +
    coord_flip()
```


```{r price-dist-per-category, echo = FALSE, warning = FALSE, message = FALSE, results = 'hide', fig.cap="A Plot Showing the Price Distribution per Category", out.width="100%"}
tidy_ikea %>%
  ggplot(aes(x = reorder(fct_lump(tidy_ikea$category, 15), price_eur), y = price_eur, colour = fct_lump(tidy_ikea$category, 15))) +
    geom_boxplot(width = 0.4, outlier.size = 0.5, outlier.alpha = 0.3,  show.legend = FALSE) +
    scale_color_manual(values = mycolors) +
    theme_minimal() +
    labs(x = "", y = "price in €", fill = "") +
    coord_flip()
```


```{r price-dist-other-colors,echo = FALSE, warning = FALSE, message = FALSE, results = 'hide', fig.cap="A Plot Showing the Price Distribution Other Colors", out.width="100%"}
knitr::opts_chunk$set(fig.pos = '!h')

tidy_ikea %>%
  ggplot(aes(x = price_eur, y = other_colors, color = other_colors)) +
  geom_boxplot(width = 0.4, outlier.size = 0.5, outlier.alpha = 0.3,  show.legend = FALSE) +
  scale_color_manual(values = mycolors) +
  theme_minimal() +
  labs(x = "price in €", y = "other_colors", fill = "")
```

```{r price-dist-sellable-online,echo = FALSE, warning = FALSE, message = FALSE, results = 'hide', fig.cap="A Plot Showing the Price Distribution Sellable Online", out.width="100%"}
tidy_ikea %>%
  ggplot(aes(x = price_eur, y = sellable_online, color = sellable_online)) +
    geom_boxplot(width = 0.4, outlier.size = 0.5, outlier.alpha = 0.3,  show.legend = FALSE) +
    scale_color_manual(values = mycolors) +
    theme_minimal() +
    labs(x = "price in €", y = "sellable_online", fill = "", title = "Price Distribution Sellable Online")
```

```{r relationship-x-y, echo = FALSE, warning = FALSE, message = FALSE, results = 'hide', fig.cap="Relationship between Independent Variables and Price", out.width="100%"}
tidy_ikea %>%
  mutate(across(where(is.character), as.factor)) %>% mutate(across(where(is.factor), as.numeric)) %>%
  # select() %>% # De-select variables here if necessary
  pivot_longer(-price_eur, names_to = "variable", values_to = "num") %>% group_by(variable) %>%
  arrange(num) %>%
  mutate(observation = 1:n()) %>%
  ungroup() %>%
  ggplot(aes(x = num, y = price_eur)) + theme_bw() +
  geom_point(shape = 1, alpha = 0.8, position = "jitter") +
  geom_smooth(se = FALSE, colour = "blue", method = "loess", formula = 'y ~ x') +
  facet_wrap(~ variable, scales = "free_x") + ylab("Price in €") + xlab("")
```






```{r coplot-code-designer-name, echo = FALSE, warning = FALSE, message = FALSE, eval = TRUE, fig.cap="Coplot of Size and Price Split by Designer and Name", out.width="100%",}
invisible(coplot(size_m3 ~ price_eur | fct_lump_n(designer, 5) + 
         fct_lump_n(name, 5), data = tidy_ikea,
       ylab = c("Size in m^3", "Name"),
       xlab = c("Price in €", "Designer"), panel = function(x, y, ...) {
         tmp <- lm(y ~ x, na.action = na.omit)
         abline(tmp)
         points(x, y )}))
```

```{r coplot-code-category-name, echo = TRUE, warning = FALSE, message = FALSE, eval = FALSE, cap="Code for Coplotting Combinations", out.width="100%"}
coplot(size_m3 ~ price_eur | fct_lump_n(category, 5) + 
         fct_lump_n(name, 5), data = drop_na(tidy_ikea), ylab = "Size in m^3",
       xlab = "Price in Euro", panel = function(x, y, ...) {
         tmp <- lm(y ~ x, na.action = na.omit)
         abline(tmp)
         points(x, y )})
```

```{r coplot-code-designer-category, warning = FALSE, message = FALSE, eval = FALSE, cap="Code for Coplotting Combinations", out.width="100%"}
coplot(size_m3 ~ price_eur | fct_lump_n(designer, 5) + 
         fct_lump_n(category, 5), data = drop_na(tidy_ikea), 
       ylab = "Size in m^3",
       xlab = "Price in €", panel = function(x, y, ...) {
         tmp <- lm(y ~ x, na.action = na.omit)
         abline(tmp)
         points(x, y )})
```


# Bibliography













